Ponya/Ponya-Back/Ponya-Back/Controllers/AuthController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Ponya_Back.DAL;
using Ponya_Back.Models;
using Ponya_Back.Utilities;
using Ponya_Back.ViewModel.Authoraztion;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ponya_Back.Controllers
{
    public class AuthController : Controller
    {
        private readonly UserManager<AppUser> _usermanager;
        private readonly SignInManager<AppUser> _signInmanager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public AuthController(UserManager<AppUser> usermanager,SignInManager<AppUser> signInmanager,RoleManager<IdentityRole> roleManager)
        {
            _usermanager = usermanager;
            _signInmanager = signInmanager;
            _roleManager = roleManager;
        }
        public IActionResult SignIn()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> SignIn(SignInVM signIn ,string ReturnUrl)
        {
            AppUser user;
            if (signIn.UsernameorEmail.Contains("@"))
            {
                user = await _usermanager.FindByEmailAsync(signIn.UsernameorEmail);
            }
            else
            {
                user = await _usermanager.FindByNameAsync(signIn.UsernameorEmail);
            }
            if(user == null)
            {
                ModelState.AddModelError("", "Password and Name is incorrect");
                return View(signIn);
            }
            var result = await _signInmanager.PasswordSignInAsync(user, signIn.Password, signIn.RememberMe, true);
            if (result.IsLockedOut)
            {
                ModelState.AddModelError("", "Sınama cəhdini aşdınız. Zəhmət olmasa biraz gözləyin");
                return View(signIn);
            }
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Login və ya parol yalnışdır");
                return View(signIn);
            }
            if (ReturnUrl != null) return LocalRedirect(ReturnUrl);
            return RedirectToAction("Index", "Home");
        }
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(RegisterVM register)
        {
            if (!ModelState.IsValid) return View();
            AppUser appUser = new AppUser
            {
                Name=register.FirstName,
                SurName=register.LastName,
                Email=register.Email,
                UserName=register.Username
            };
            IdentityResult result = await _usermanager.CreateAsync(appUser, register.Password);
            if (!result.Succeeded)
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }
            }
            await _usermanager.AddToRoleAsync(appUser, UserRoles.Admin.ToString());
            return RedirectToAction("Index", "Home");
        }
        public  async Task<IActionResult> SignOut()
        {
            await _signInmanager.SignOutAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task CreateRoles()
        {
            foreach (var item in Enum.GetValues(typeof(UserRoles)))
            {
                if (!await _roleManager.RoleExistsAsync(item.ToString())) await _roleManager.CreateAsync(new IdentityRole(item.ToString()));
            }
        }
    }
}

Ponya/Ponya-Back/Ponya-Back/Controllers/BlogController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Ponya_Back.DAL;
using Ponya_Back.ViewModel.BlogViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ponya_Back.Controllers
{
    public class BlogController : Controller
    {
        private readonly AppDbContext _context;

        public BlogController(AppDbContext context)
        {
            _context = context;
        }
        // GET: BlogController
        public ActionResult Index()
        {
            BlogVM blogVM = new BlogVM
            {
                Blogs= _context.Blogs.Include(c=>c.BlogCategory).Where(x=>x.IsDeleted==false).Take(6).ToList()
            };
            return View(blogVM);
        }

        
    }
}

Ponya/Ponya-Back/Ponya-Back/Views/Shared/_Layout.cshtml
@using Ponya_Back.Services
@inject LayoutServices service
@{ 
    Dictionary<string, string> settings = service.GetSettings();
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/assets/css/style.css">
    <title>Ponya</title>
</head>

<body>
    <main>
        <!-- Header -->
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container">
                <img src="~/assets/image/header/@settings["Logo"]" width="150" height="50" alt="">
                <button class="navbar-toggler h-25" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse ms-5 " id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 ms-5 gap-4  mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active fw-bold main-color" aria-current="page" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  fw-bold" asp-controller="About" asp-action="Index">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  fw-bold" asp-controller="Blog" asp-action="Index">Blog</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle  fw-bold" href="#" id="navbarDropdown" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                Portfolio
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item  fw-bold" asp-controller="Portfolio" asp-action="Index">Portfolio</a></li>
                                <li>
                                    <a class="dropdown-item fw-bold" asp-controller="PortfolioDetail" asp-action="Index">Portfolio Detail </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link fw-bold " asp-controller="Service" asp-action="Index">Service</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle fw-bold" href="#" id="navbarDropdown" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                Pages
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">                        
                                <li><a class="dropdown-item fw-bold" asp-controller="404" asp-action="Index">404 </a></li>
                            </ul>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle  fw-bold" href="#" id="navbarDropdown" role="button"
                                   data-bs-toggle="dropdown" aria-expanded="false">
                                    My Account
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li>
                                        <a class="dropdown-item  fw-bold"><i class="bi bi-person-circle"></i>@User.Identity.Name</a>
                                    </li>
                                    <li>
                                        <a asp-controller="Auth" asp-action="SignOut" class="dropdown-item fw-bold"><i class="bi bi-door-open-fill"></i> Sign Out</a>
                                    </li>
                                </ul>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a asp-controller="Auth" asp-action="SignIn" asp-route-ReturnUrl="@Context.Request.Path" class="nav-link fw-bold " >Login</a>
                            </li>
                        }


                        <li class="nav-item">
                            <button class="nav-link btn main-bgcolor fw-bold text-white contactbtn">
                                <a asp-controller="Contact" asp-action="Index" class="text-decoration-none text-white">Contact Us</a>
                            </button>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
        @RenderBody()
        <!-- Footer -->
        <footer class="pt-5 w-100  bg-dark">
            <div class="container pt-4">
                <div class="row pt-4">
                    <div class="col-md-3">
                        <img src="~/assets/image/header/logo-8.png" alt="">
                        <p class="pt-3 text-white">Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
                        <ul class="row pt-2">
                            <li class="col list-unstyled text-white kl fs-3"><i class="@settings["FacebookIcon"]"><a href="@settings["FacebookUrl"]"></a></i></li>
                            <li class="col list-unstyled text-white kl fs-3"><i class="@settings["TwitterIcon"]"></i><a href="@settings["TwitterUrl"]"></a></li>
                            <li class="col list-unstyled text-white kl fs-3"><i class="@settings["YoutubeIcon"]"></i><a href="@settings["YoutubeUrl"]"></a></li>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <h4 class="text-white">About</h4>
                        <ul class="col me-5">
                            <li class="row list-unstyled nav-link text-white fs-5">About</li>
                            <li class="row list-unstyled nav-link text-white fs-5">Blog</li>
                            <li class="row list-unstyled nav-link text-white fs-5">Service</li>
                            <li class="row list-unstyled nav-link text-white fs-5">Portfolio</li>
                            <li class="row list-unstyled nav-link text-white fs-5">Contact</li>
                        </ul>

                    </div>
                    <div class="col-md-3">
                        <h4 class="text-white">Company</h4>
                        <ul class="col me-5">
                            <li class="row list-unstyled nav-link text-white fs-5">Terms & Conditions</li>
                            <li class="row list-unstyled nav-link text-white fs-5">Privacy Policy</li>
                            <li class="row list-unstyled nav-link text-white fs-5">Press Release</li>
                            <li class="row list-unstyled nav-link text-white fs-5"><a asp-area="Manage" asp-controller="Hero" asp-action="Index">Affiliates</a></li>

                        </ul>
                    </div>
                    <div class="col-md-3">
                        <h4 class="text-white">Newsletter</h4>
                        <input type="email" placeholder="Email" class="form-control mb-4">
                        <button type="submit" class="btn btn-outline-narinci form-control-lg main-color">Subscribe</button>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Disagn -->
        <footer class="bg-black text-xxl-center">
            <p class="text-white">Copyright © 2022 Ponya | Disagned by Mahammad</p>
        </footer>
    </main>
    <script src="~/assets/js/main.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popperjs/core@2.11.5/dist/umd/popper.min.js"
            integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js"
            integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy"
            crossorigin="anonymous"></script>
</body>

</html>

Ponya/Ponya-Back/Ponya-Back/Views/Shared/_PricingPartial.cshtml
<div class="row pt-4">
    <div class="col-md-3">
        <h3 class="text-dark fs-2">Flexible</h3>
        <h3 class="text-dark fs-2">pricing plans</h3>
        <p class="pt-4">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus
            nec ullamcorper mattis, pulvinar dapibus leo.
        </p>
        <span class="ms-3 main-color gh coruier fs-5">
            <i class="bi bi-box fs-5"></i>Explore
            features
        </span>
    </div>
    <div class="col-md-3 bg-light text-xxl-center rounded-2">
        <h4 class="text-dark pt-3 ">Pricing Table</h4>
        <div class="bg-light text-white">gccccccd</div>
        <span class="main-color fs-4">$ <span class="fs-65 tahoma">199</span> <span>/m</span></span>
        <p class="text-dark "><i class="bi bi-check"></i>5 Channel</p>
        <p class="text-dark"><i class="bi bi-check"></i>Inbox Support</p>
        <p class="text-dark"><i class="bi bi-check"></i>Content Plan</p>
        <p class="text-dark"><i class="bi bi-x"></i>Pixel Installation</p>
        <p class="text-dark"><i class="bi bi-x"></i>Advertising</p>
        <button class="pt-3 hj btn form-control fw-bold bg-dark text-white ">Get Stated</button>
        <hr>
    </div>
    <div class="col-md-3 main-bgcolor text-xxl-center rounded-2">
        <h4 class="text-white pt-3 ">Pricing Table</h4>
        <div class="bg-white main-color">New</div>
        <del class="text-white fs-5">399</del><span class="text-white fs-4">
            $ <span class="fs-65 tahoma">199</span> <span>/m</span>
        </span>
        <p class="text-white "><i class="bi bi-check"></i>10 Channel</p>
        <p class="text-white"><i class="bi bi-check"></i>Inbox Support</p>
        <p class="text-white"><i class="bi bi-check"></i>Content Plan</p>
        <p class="text-white"><i class="bi bi-x"></i>Pixel Installation</p>
        <p class="text-white"><i class="bi bi-x"></i>Advertising</p>
        <button class="pt-3  btn form-control fw-bold bg-white main-color ">Get Stated</button>
        <hr>
    </div>
    <div class="col-md-3 bg-light text-xxl-center rounded-2">
        <h4 class="text-dark pt-3 ">Pricing Table</h4>
        <div class="text-white main-bgcolor">Limited</div>
        <del class="text-dark fs-5">699</del><span class="main-color fs-4">
            $ <span class="fs-65 tahoma">499</span> <span>/m</span>
        </span>
        <p class="text-dark "><i class="bi bi-check"></i>20 Channel</p>
        <p class="text-dark"><i class="bi bi-check"></i>Inbox Support</p>
        <p class="text-dark"><i class="bi bi-check"></i>Content Plan</p>
        <p class="text-dark"><i class="bi bi-check"></i>Pixel Installation</p>
        <p class="text-dark"><i class="bi bi-check"></i>Advertising</p>
        <button class="pt-3 hj btn form-control fw-bold bg-dark text-white ">Get Stated</button>
        <hr>
    </div>
</div>